# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x08\x61pi_spec\x1a\x1egoogle/protobuf/wrappers.proto\" \n\x08\x42oolType\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x08\"!\n\tBytesType\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x0c\"1\n\nStringType\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\t\x12\r\n\x05regex\x18\x02 \x01(\t\"u\n\tInt32Type\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x05\x12(\n\x03min\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12(\n\x03max\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\"u\n\tInt64Type\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x03\x12(\n\x03min\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12(\n\x03max\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\"x\n\nUint32Type\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\r\x12)\n\x03min\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12)\n\x03max\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"x\n\nUint64Type\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x04\x12)\n\x03min\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\x12)\n\x03max\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.UInt64Value\"x\n\nDoubleType\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x01\x12)\n\x03min\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12)\n\x03max\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"u\n\tFloatType\x12\x14\n\x0c\x66ixed_values\x18\x01 \x03(\x02\x12(\n\x03min\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12(\n\x03max\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\"1\n\x0c\x46ormatOption\x12\x17\n\rstring_format\x18\x01 \x01(\tH\x00\x42\x08\n\x06\x66ormat\"h\n\x10\x41kitaAnnotations\x12\x0f\n\x07is_free\x18\x01 \x01(\x08\x12\x14\n\x0cis_sensitive\x18\x02 \x01(\x08\x12-\n\rformat_option\x18\x03 \x01(\x0b\x32\x16.api_spec.FormatOptionB,Z*akitasoftware.com/superstar/pb/go/api_specb\x06proto3')



_BOOLTYPE = DESCRIPTOR.message_types_by_name['BoolType']
_BYTESTYPE = DESCRIPTOR.message_types_by_name['BytesType']
_STRINGTYPE = DESCRIPTOR.message_types_by_name['StringType']
_INT32TYPE = DESCRIPTOR.message_types_by_name['Int32Type']
_INT64TYPE = DESCRIPTOR.message_types_by_name['Int64Type']
_UINT32TYPE = DESCRIPTOR.message_types_by_name['Uint32Type']
_UINT64TYPE = DESCRIPTOR.message_types_by_name['Uint64Type']
_DOUBLETYPE = DESCRIPTOR.message_types_by_name['DoubleType']
_FLOATTYPE = DESCRIPTOR.message_types_by_name['FloatType']
_FORMATOPTION = DESCRIPTOR.message_types_by_name['FormatOption']
_AKITAANNOTATIONS = DESCRIPTOR.message_types_by_name['AkitaAnnotations']
BoolType = _reflection.GeneratedProtocolMessageType('BoolType', (_message.Message,), {
  'DESCRIPTOR' : _BOOLTYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.BoolType)
  })
_sym_db.RegisterMessage(BoolType)

BytesType = _reflection.GeneratedProtocolMessageType('BytesType', (_message.Message,), {
  'DESCRIPTOR' : _BYTESTYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.BytesType)
  })
_sym_db.RegisterMessage(BytesType)

StringType = _reflection.GeneratedProtocolMessageType('StringType', (_message.Message,), {
  'DESCRIPTOR' : _STRINGTYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.StringType)
  })
_sym_db.RegisterMessage(StringType)

Int32Type = _reflection.GeneratedProtocolMessageType('Int32Type', (_message.Message,), {
  'DESCRIPTOR' : _INT32TYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.Int32Type)
  })
_sym_db.RegisterMessage(Int32Type)

Int64Type = _reflection.GeneratedProtocolMessageType('Int64Type', (_message.Message,), {
  'DESCRIPTOR' : _INT64TYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.Int64Type)
  })
_sym_db.RegisterMessage(Int64Type)

Uint32Type = _reflection.GeneratedProtocolMessageType('Uint32Type', (_message.Message,), {
  'DESCRIPTOR' : _UINT32TYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.Uint32Type)
  })
_sym_db.RegisterMessage(Uint32Type)

Uint64Type = _reflection.GeneratedProtocolMessageType('Uint64Type', (_message.Message,), {
  'DESCRIPTOR' : _UINT64TYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.Uint64Type)
  })
_sym_db.RegisterMessage(Uint64Type)

DoubleType = _reflection.GeneratedProtocolMessageType('DoubleType', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLETYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.DoubleType)
  })
_sym_db.RegisterMessage(DoubleType)

FloatType = _reflection.GeneratedProtocolMessageType('FloatType', (_message.Message,), {
  'DESCRIPTOR' : _FLOATTYPE,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.FloatType)
  })
_sym_db.RegisterMessage(FloatType)

FormatOption = _reflection.GeneratedProtocolMessageType('FormatOption', (_message.Message,), {
  'DESCRIPTOR' : _FORMATOPTION,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.FormatOption)
  })
_sym_db.RegisterMessage(FormatOption)

AkitaAnnotations = _reflection.GeneratedProtocolMessageType('AkitaAnnotations', (_message.Message,), {
  'DESCRIPTOR' : _AKITAANNOTATIONS,
  '__module__' : 'types_pb2'
  # @@protoc_insertion_point(class_scope:api_spec.AkitaAnnotations)
  })
_sym_db.RegisterMessage(AkitaAnnotations)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*akitasoftware.com/superstar/pb/go/api_spec'
  _BOOLTYPE._serialized_start=57
  _BOOLTYPE._serialized_end=89
  _BYTESTYPE._serialized_start=91
  _BYTESTYPE._serialized_end=124
  _STRINGTYPE._serialized_start=126
  _STRINGTYPE._serialized_end=175
  _INT32TYPE._serialized_start=177
  _INT32TYPE._serialized_end=294
  _INT64TYPE._serialized_start=296
  _INT64TYPE._serialized_end=413
  _UINT32TYPE._serialized_start=415
  _UINT32TYPE._serialized_end=535
  _UINT64TYPE._serialized_start=537
  _UINT64TYPE._serialized_end=657
  _DOUBLETYPE._serialized_start=659
  _DOUBLETYPE._serialized_end=779
  _FLOATTYPE._serialized_start=781
  _FLOATTYPE._serialized_end=898
  _FORMATOPTION._serialized_start=900
  _FORMATOPTION._serialized_end=949
  _AKITAANNOTATIONS._serialized_start=951
  _AKITAANNOTATIONS._serialized_end=1055
# @@protoc_insertion_point(module_scope)
