// Code generated by protoc-gen-go. DO NOT EDIT.
// source: method.proto

package api_spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HTTPAuth_HTTPAuthType int32

const (
	HTTPAuth_UNKNOWN HTTPAuth_HTTPAuthType = 0
	HTTPAuth_BASIC   HTTPAuth_HTTPAuthType = 1
	HTTPAuth_BEARER  HTTPAuth_HTTPAuthType = 2
)

var HTTPAuth_HTTPAuthType_name = map[int32]string{
	0: "UNKNOWN",
	1: "BASIC",
	2: "BEARER",
}

var HTTPAuth_HTTPAuthType_value = map[string]int32{
	"UNKNOWN": 0,
	"BASIC":   1,
	"BEARER":  2,
}

func (x HTTPAuth_HTTPAuthType) String() string {
	return proto.EnumName(HTTPAuth_HTTPAuthType_name, int32(x))
}

func (HTTPAuth_HTTPAuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{19, 0}
}

type HTTPBody_ContentType int32

const (
	HTTPBody_UNKNOWN          HTTPBody_ContentType = 0
	HTTPBody_JSON             HTTPBody_ContentType = 1
	HTTPBody_FORM_URL_ENCODED HTTPBody_ContentType = 2
	HTTPBody_OCTET_STREAM     HTTPBody_ContentType = 3
	HTTPBody_PDF              HTTPBody_ContentType = 4
	HTTPBody_TEXT_PLAIN       HTTPBody_ContentType = 5
	HTTPBody_YAML             HTTPBody_ContentType = 6
)

var HTTPBody_ContentType_name = map[int32]string{
	0: "UNKNOWN",
	1: "JSON",
	2: "FORM_URL_ENCODED",
	3: "OCTET_STREAM",
	4: "PDF",
	5: "TEXT_PLAIN",
	6: "YAML",
}

var HTTPBody_ContentType_value = map[string]int32{
	"UNKNOWN":          0,
	"JSON":             1,
	"FORM_URL_ENCODED": 2,
	"OCTET_STREAM":     3,
	"PDF":              4,
	"TEXT_PLAIN":       5,
	"YAML":             6,
}

func (x HTTPBody_ContentType) String() string {
	return proto.EnumName(HTTPBody_ContentType_name, int32(x))
}

func (HTTPBody_ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{21, 0}
}

type Bool struct {
	Type                 *BoolType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                bool      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{0}
}

func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetType() *BoolType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Bytes struct {
	Type                 *BytesType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{1}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetType() *BytesType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Bytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type String struct {
	Type                 *StringType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                string      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{2}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetType() *StringType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Int32 struct {
	Type                 *Int32Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                int32      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{3}
}

func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (m *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(m, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetType() *Int32Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64 struct {
	Type                 *Int64Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                int64      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{4}
}

func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetType() *Int64Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint32 struct {
	Type                 *Uint32Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                uint32      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Uint32) Reset()         { *m = Uint32{} }
func (m *Uint32) String() string { return proto.CompactTextString(m) }
func (*Uint32) ProtoMessage()    {}
func (*Uint32) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{5}
}

func (m *Uint32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint32.Unmarshal(m, b)
}
func (m *Uint32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint32.Marshal(b, m, deterministic)
}
func (m *Uint32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint32.Merge(m, src)
}
func (m *Uint32) XXX_Size() int {
	return xxx_messageInfo_Uint32.Size(m)
}
func (m *Uint32) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint32.DiscardUnknown(m)
}

var xxx_messageInfo_Uint32 proto.InternalMessageInfo

func (m *Uint32) GetType() *Uint32Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Uint32) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Uint64 struct {
	Type                 *Uint64Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                uint64      `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Uint64) Reset()         { *m = Uint64{} }
func (m *Uint64) String() string { return proto.CompactTextString(m) }
func (*Uint64) ProtoMessage()    {}
func (*Uint64) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{6}
}

func (m *Uint64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uint64.Unmarshal(m, b)
}
func (m *Uint64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uint64.Marshal(b, m, deterministic)
}
func (m *Uint64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uint64.Merge(m, src)
}
func (m *Uint64) XXX_Size() int {
	return xxx_messageInfo_Uint64.Size(m)
}
func (m *Uint64) XXX_DiscardUnknown() {
	xxx_messageInfo_Uint64.DiscardUnknown(m)
}

var xxx_messageInfo_Uint64 proto.InternalMessageInfo

func (m *Uint64) GetType() *Uint64Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Uint64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Double struct {
	Type                 *DoubleType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                float64     `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Double) Reset()         { *m = Double{} }
func (m *Double) String() string { return proto.CompactTextString(m) }
func (*Double) ProtoMessage()    {}
func (*Double) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{7}
}

func (m *Double) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Double.Unmarshal(m, b)
}
func (m *Double) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Double.Marshal(b, m, deterministic)
}
func (m *Double) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Double.Merge(m, src)
}
func (m *Double) XXX_Size() int {
	return xxx_messageInfo_Double.Size(m)
}
func (m *Double) XXX_DiscardUnknown() {
	xxx_messageInfo_Double.DiscardUnknown(m)
}

var xxx_messageInfo_Double proto.InternalMessageInfo

func (m *Double) GetType() *DoubleType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Double) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Float struct {
	Type                 *FloatType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                float32    `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Float) Reset()         { *m = Float{} }
func (m *Float) String() string { return proto.CompactTextString(m) }
func (*Float) ProtoMessage()    {}
func (*Float) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{8}
}

func (m *Float) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Float.Unmarshal(m, b)
}
func (m *Float) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Float.Marshal(b, m, deterministic)
}
func (m *Float) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Float.Merge(m, src)
}
func (m *Float) XXX_Size() int {
	return xxx_messageInfo_Float.Size(m)
}
func (m *Float) XXX_DiscardUnknown() {
	xxx_messageInfo_Float.DiscardUnknown(m)
}

var xxx_messageInfo_Float proto.InternalMessageInfo

func (m *Float) GetType() *FloatType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Float) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Primitive struct {
	TypeHint string `protobuf:"bytes,1,opt,name=type_hint,json=typeHint,proto3" json:"type_hint,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Primitive_BoolValue
	//	*Primitive_BytesValue
	//	*Primitive_StringValue
	//	*Primitive_Int32Value
	//	*Primitive_Int64Value
	//	*Primitive_Uint32Value
	//	*Primitive_Uint64Value
	//	*Primitive_DoubleValue
	//	*Primitive_FloatValue
	Value            isPrimitive_Value `protobuf_oneof:"value"`
	AkitaAnnotations *AkitaAnnotations `protobuf:"bytes,11,opt,name=akita_annotations,json=akitaAnnotations,proto3" json:"akita_annotations,omitempty"`
	// If true, indicates that the value of this primitive was randomly generated.
	// When making API calls against a target system whose state cannot be reset,
	// the API caller may choose to generate a new random value to avoid the old
	// value from invalidating the API call (e.g. creating an object with the same
	// name). It's unlikely that the target system would behave differently
	// depending on a random value, so we think this is a viable workaround.
	// Note that we chose this approach instead of stop generating random values
	// upfront because if we encounter a target system that supports reset, the
	// fixed random values adds extra assurance to reproducibility.
	ContainsRandomValue bool `protobuf:"varint,12,opt,name=contains_random_value,json=containsRandomValue,proto3" json:"contains_random_value,omitempty"`
	// Values of this Primitive must match one of these data formats, if present.
	// An empty map means no restrictions on format.
	//
	// This is typed as a map to ensure stable hashing.  Values should always be
	// `true`.
	//
	// Data format definitions:
	// https://github.com/akitasoftware/test-service/blob/master/lib/data_formats/data_formats.go
	Formats map[string]bool `protobuf:"bytes,13,rep,name=formats,proto3" json:"formats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// Format kinds describe collections of formats, e.g. datetime is the kind
	// of various date formats, e.g. RFC3339 and Unix-style timestamps.
	//
	// Data format kind definitions:
	// https://github.com/akitasoftware/test-service/blob/master/lib/data_formats/data_formats.go
	FormatKind           string   `protobuf:"bytes,14,opt,name=format_kind,json=formatKind,proto3" json:"format_kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Primitive) Reset()         { *m = Primitive{} }
func (m *Primitive) String() string { return proto.CompactTextString(m) }
func (*Primitive) ProtoMessage()    {}
func (*Primitive) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{9}
}

func (m *Primitive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Primitive.Unmarshal(m, b)
}
func (m *Primitive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Primitive.Marshal(b, m, deterministic)
}
func (m *Primitive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Primitive.Merge(m, src)
}
func (m *Primitive) XXX_Size() int {
	return xxx_messageInfo_Primitive.Size(m)
}
func (m *Primitive) XXX_DiscardUnknown() {
	xxx_messageInfo_Primitive.DiscardUnknown(m)
}

var xxx_messageInfo_Primitive proto.InternalMessageInfo

func (m *Primitive) GetTypeHint() string {
	if m != nil {
		return m.TypeHint
	}
	return ""
}

type isPrimitive_Value interface {
	isPrimitive_Value()
}

type Primitive_BoolValue struct {
	BoolValue *Bool `protobuf:"bytes,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Primitive_BytesValue struct {
	BytesValue *Bytes `protobuf:"bytes,3,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Primitive_StringValue struct {
	StringValue *String `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Primitive_Int32Value struct {
	Int32Value *Int32 `protobuf:"bytes,5,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Primitive_Int64Value struct {
	Int64Value *Int64 `protobuf:"bytes,6,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Primitive_Uint32Value struct {
	Uint32Value *Uint32 `protobuf:"bytes,7,opt,name=uint32_value,json=uint32Value,proto3,oneof"`
}

type Primitive_Uint64Value struct {
	Uint64Value *Uint64 `protobuf:"bytes,8,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

type Primitive_DoubleValue struct {
	DoubleValue *Double `protobuf:"bytes,9,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Primitive_FloatValue struct {
	FloatValue *Float `protobuf:"bytes,10,opt,name=float_value,json=floatValue,proto3,oneof"`
}

func (*Primitive_BoolValue) isPrimitive_Value() {}

func (*Primitive_BytesValue) isPrimitive_Value() {}

func (*Primitive_StringValue) isPrimitive_Value() {}

func (*Primitive_Int32Value) isPrimitive_Value() {}

func (*Primitive_Int64Value) isPrimitive_Value() {}

func (*Primitive_Uint32Value) isPrimitive_Value() {}

func (*Primitive_Uint64Value) isPrimitive_Value() {}

func (*Primitive_DoubleValue) isPrimitive_Value() {}

func (*Primitive_FloatValue) isPrimitive_Value() {}

func (m *Primitive) GetValue() isPrimitive_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Primitive) GetBoolValue() *Bool {
	if x, ok := m.GetValue().(*Primitive_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *Primitive) GetBytesValue() *Bytes {
	if x, ok := m.GetValue().(*Primitive_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Primitive) GetStringValue() *String {
	if x, ok := m.GetValue().(*Primitive_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *Primitive) GetInt32Value() *Int32 {
	if x, ok := m.GetValue().(*Primitive_Int32Value); ok {
		return x.Int32Value
	}
	return nil
}

func (m *Primitive) GetInt64Value() *Int64 {
	if x, ok := m.GetValue().(*Primitive_Int64Value); ok {
		return x.Int64Value
	}
	return nil
}

func (m *Primitive) GetUint32Value() *Uint32 {
	if x, ok := m.GetValue().(*Primitive_Uint32Value); ok {
		return x.Uint32Value
	}
	return nil
}

func (m *Primitive) GetUint64Value() *Uint64 {
	if x, ok := m.GetValue().(*Primitive_Uint64Value); ok {
		return x.Uint64Value
	}
	return nil
}

func (m *Primitive) GetDoubleValue() *Double {
	if x, ok := m.GetValue().(*Primitive_DoubleValue); ok {
		return x.DoubleValue
	}
	return nil
}

func (m *Primitive) GetFloatValue() *Float {
	if x, ok := m.GetValue().(*Primitive_FloatValue); ok {
		return x.FloatValue
	}
	return nil
}

func (m *Primitive) GetAkitaAnnotations() *AkitaAnnotations {
	if m != nil {
		return m.AkitaAnnotations
	}
	return nil
}

func (m *Primitive) GetContainsRandomValue() bool {
	if m != nil {
		return m.ContainsRandomValue
	}
	return false
}

func (m *Primitive) GetFormats() map[string]bool {
	if m != nil {
		return m.Formats
	}
	return nil
}

func (m *Primitive) GetFormatKind() string {
	if m != nil {
		return m.FormatKind
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Primitive) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Primitive_BoolValue)(nil),
		(*Primitive_BytesValue)(nil),
		(*Primitive_StringValue)(nil),
		(*Primitive_Int32Value)(nil),
		(*Primitive_Int64Value)(nil),
		(*Primitive_Uint32Value)(nil),
		(*Primitive_Uint64Value)(nil),
		(*Primitive_DoubleValue)(nil),
		(*Primitive_FloatValue)(nil),
	}
}

type List struct {
	Elems                []*Data  `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{10}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetElems() []*Data {
	if m != nil {
		return m.Elems
	}
	return nil
}

type Struct struct {
	Fields               map[string]*Data `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Struct) Reset()         { *m = Struct{} }
func (m *Struct) String() string { return proto.CompactTextString(m) }
func (*Struct) ProtoMessage()    {}
func (*Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{11}
}

func (m *Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Struct.Unmarshal(m, b)
}
func (m *Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Struct.Marshal(b, m, deterministic)
}
func (m *Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct.Merge(m, src)
}
func (m *Struct) XXX_Size() int {
	return xxx_messageInfo_Struct.Size(m)
}
func (m *Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Struct proto.InternalMessageInfo

func (m *Struct) GetFields() map[string]*Data {
	if m != nil {
		return m.Fields
	}
	return nil
}

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{12}
}

func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type Optional struct {
	// Types that are valid to be assigned to Value:
	//	*Optional_Data
	//	*Optional_None
	Value                isOptional_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Optional) Reset()         { *m = Optional{} }
func (m *Optional) String() string { return proto.CompactTextString(m) }
func (*Optional) ProtoMessage()    {}
func (*Optional) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{13}
}

func (m *Optional) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Optional.Unmarshal(m, b)
}
func (m *Optional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Optional.Marshal(b, m, deterministic)
}
func (m *Optional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Optional.Merge(m, src)
}
func (m *Optional) XXX_Size() int {
	return xxx_messageInfo_Optional.Size(m)
}
func (m *Optional) XXX_DiscardUnknown() {
	xxx_messageInfo_Optional.DiscardUnknown(m)
}

var xxx_messageInfo_Optional proto.InternalMessageInfo

type isOptional_Value interface {
	isOptional_Value()
}

type Optional_Data struct {
	Data *Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type Optional_None struct {
	None *None `protobuf:"bytes,2,opt,name=none,proto3,oneof"`
}

func (*Optional_Data) isOptional_Value() {}

func (*Optional_None) isOptional_Value() {}

func (m *Optional) GetValue() isOptional_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Optional) GetData() *Data {
	if x, ok := m.GetValue().(*Optional_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Optional) GetNone() *None {
	if x, ok := m.GetValue().(*Optional_None); ok {
		return x.None
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Optional) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Optional_Data)(nil),
		(*Optional_None)(nil),
	}
}

type OneOf struct {
	// Map keys are the hashes of the Data values. This allows us to stably
	// compare OneOf messages and ensure there are no duplicate options.
	// See hash function at:
	// https://github.com/akitasoftware/test-service/blob/master/lib/pbhash/pbhash.go
	Options map[string]*Data `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// True if this oneof was created by Akita during learn mode to encode a
	// potential conflict in the API spec.
	PotentialConflict    bool     `protobuf:"varint,2,opt,name=potential_conflict,json=potentialConflict,proto3" json:"potential_conflict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneOf) Reset()         { *m = OneOf{} }
func (m *OneOf) String() string { return proto.CompactTextString(m) }
func (*OneOf) ProtoMessage()    {}
func (*OneOf) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{14}
}

func (m *OneOf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneOf.Unmarshal(m, b)
}
func (m *OneOf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneOf.Marshal(b, m, deterministic)
}
func (m *OneOf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneOf.Merge(m, src)
}
func (m *OneOf) XXX_Size() int {
	return xxx_messageInfo_OneOf.Size(m)
}
func (m *OneOf) XXX_DiscardUnknown() {
	xxx_messageInfo_OneOf.DiscardUnknown(m)
}

var xxx_messageInfo_OneOf proto.InternalMessageInfo

func (m *OneOf) GetOptions() map[string]*Data {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *OneOf) GetPotentialConflict() bool {
	if m != nil {
		return m.PotentialConflict
	}
	return false
}

type GRPCMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCMeta) Reset()         { *m = GRPCMeta{} }
func (m *GRPCMeta) String() string { return proto.CompactTextString(m) }
func (*GRPCMeta) ProtoMessage()    {}
func (*GRPCMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{15}
}

func (m *GRPCMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCMeta.Unmarshal(m, b)
}
func (m *GRPCMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCMeta.Marshal(b, m, deterministic)
}
func (m *GRPCMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCMeta.Merge(m, src)
}
func (m *GRPCMeta) XXX_Size() int {
	return xxx_messageInfo_GRPCMeta.Size(m)
}
func (m *GRPCMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCMeta.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCMeta proto.InternalMessageInfo

type HTTPPath struct {
	// Path parameter name
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPPath) Reset()         { *m = HTTPPath{} }
func (m *HTTPPath) String() string { return proto.CompactTextString(m) }
func (*HTTPPath) ProtoMessage()    {}
func (*HTTPPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{16}
}

func (m *HTTPPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPPath.Unmarshal(m, b)
}
func (m *HTTPPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPPath.Marshal(b, m, deterministic)
}
func (m *HTTPPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPPath.Merge(m, src)
}
func (m *HTTPPath) XXX_Size() int {
	return xxx_messageInfo_HTTPPath.Size(m)
}
func (m *HTTPPath) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPPath.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPPath proto.InternalMessageInfo

func (m *HTTPPath) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type HTTPQuery struct {
	// Query parameter name
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPQuery) Reset()         { *m = HTTPQuery{} }
func (m *HTTPQuery) String() string { return proto.CompactTextString(m) }
func (*HTTPQuery) ProtoMessage()    {}
func (*HTTPQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{17}
}

func (m *HTTPQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPQuery.Unmarshal(m, b)
}
func (m *HTTPQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPQuery.Marshal(b, m, deterministic)
}
func (m *HTTPQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPQuery.Merge(m, src)
}
func (m *HTTPQuery) XXX_Size() int {
	return xxx_messageInfo_HTTPQuery.Size(m)
}
func (m *HTTPQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPQuery.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPQuery proto.InternalMessageInfo

func (m *HTTPQuery) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Note: Authorization header should go into HTTPAuth, not HTTPHeader
type HTTPHeader struct {
	// Header name
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPHeader) Reset()         { *m = HTTPHeader{} }
func (m *HTTPHeader) String() string { return proto.CompactTextString(m) }
func (*HTTPHeader) ProtoMessage()    {}
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{18}
}

func (m *HTTPHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPHeader.Unmarshal(m, b)
}
func (m *HTTPHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPHeader.Marshal(b, m, deterministic)
}
func (m *HTTPHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPHeader.Merge(m, src)
}
func (m *HTTPHeader) XXX_Size() int {
	return xxx_messageInfo_HTTPHeader.Size(m)
}
func (m *HTTPHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPHeader proto.InternalMessageInfo

func (m *HTTPHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type HTTPAuth struct {
	Type                 HTTPAuth_HTTPAuthType `protobuf:"varint,1,opt,name=type,proto3,enum=api_spec.HTTPAuth_HTTPAuthType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *HTTPAuth) Reset()         { *m = HTTPAuth{} }
func (m *HTTPAuth) String() string { return proto.CompactTextString(m) }
func (*HTTPAuth) ProtoMessage()    {}
func (*HTTPAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{19}
}

func (m *HTTPAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPAuth.Unmarshal(m, b)
}
func (m *HTTPAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPAuth.Marshal(b, m, deterministic)
}
func (m *HTTPAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPAuth.Merge(m, src)
}
func (m *HTTPAuth) XXX_Size() int {
	return xxx_messageInfo_HTTPAuth.Size(m)
}
func (m *HTTPAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPAuth.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPAuth proto.InternalMessageInfo

func (m *HTTPAuth) GetType() HTTPAuth_HTTPAuthType {
	if m != nil {
		return m.Type
	}
	return HTTPAuth_UNKNOWN
}

type HTTPCookie struct {
	// Cookie parameter name
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPCookie) Reset()         { *m = HTTPCookie{} }
func (m *HTTPCookie) String() string { return proto.CompactTextString(m) }
func (*HTTPCookie) ProtoMessage()    {}
func (*HTTPCookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{20}
}

func (m *HTTPCookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPCookie.Unmarshal(m, b)
}
func (m *HTTPCookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPCookie.Marshal(b, m, deterministic)
}
func (m *HTTPCookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPCookie.Merge(m, src)
}
func (m *HTTPCookie) XXX_Size() int {
	return xxx_messageInfo_HTTPCookie.Size(m)
}
func (m *HTTPCookie) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPCookie.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPCookie proto.InternalMessageInfo

func (m *HTTPCookie) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Represents HTTP body or a part in a multipart body.
type HTTPBody struct {
	ContentType          HTTPBody_ContentType `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3,enum=api_spec.HTTPBody_ContentType" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HTTPBody) Reset()         { *m = HTTPBody{} }
func (m *HTTPBody) String() string { return proto.CompactTextString(m) }
func (*HTTPBody) ProtoMessage()    {}
func (*HTTPBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{21}
}

func (m *HTTPBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPBody.Unmarshal(m, b)
}
func (m *HTTPBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPBody.Marshal(b, m, deterministic)
}
func (m *HTTPBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPBody.Merge(m, src)
}
func (m *HTTPBody) XXX_Size() int {
	return xxx_messageInfo_HTTPBody.Size(m)
}
func (m *HTTPBody) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPBody.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPBody proto.InternalMessageInfo

func (m *HTTPBody) GetContentType() HTTPBody_ContentType {
	if m != nil {
		return m.ContentType
	}
	return HTTPBody_UNKNOWN
}

type HTTPMultipart struct {
	// "form-data" or "mixed"
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPMultipart) Reset()         { *m = HTTPMultipart{} }
func (m *HTTPMultipart) String() string { return proto.CompactTextString(m) }
func (*HTTPMultipart) ProtoMessage()    {}
func (*HTTPMultipart) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{22}
}

func (m *HTTPMultipart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPMultipart.Unmarshal(m, b)
}
func (m *HTTPMultipart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPMultipart.Marshal(b, m, deterministic)
}
func (m *HTTPMultipart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPMultipart.Merge(m, src)
}
func (m *HTTPMultipart) XXX_Size() int {
	return xxx_messageInfo_HTTPMultipart.Size(m)
}
func (m *HTTPMultipart) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPMultipart.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPMultipart proto.InternalMessageInfo

func (m *HTTPMultipart) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type HTTPEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPEmpty) Reset()         { *m = HTTPEmpty{} }
func (m *HTTPEmpty) String() string { return proto.CompactTextString(m) }
func (*HTTPEmpty) ProtoMessage()    {}
func (*HTTPEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{23}
}

func (m *HTTPEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPEmpty.Unmarshal(m, b)
}
func (m *HTTPEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPEmpty.Marshal(b, m, deterministic)
}
func (m *HTTPEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPEmpty.Merge(m, src)
}
func (m *HTTPEmpty) XXX_Size() int {
	return xxx_messageInfo_HTTPEmpty.Size(m)
}
func (m *HTTPEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPEmpty proto.InternalMessageInfo

type HTTPMeta struct {
	// Should never be HTTPPath or HTTPQuery if this metadata is for a response.
	// Should never be HTTPEmpty if this metadata is for an argument or for a
	// response that contains headers, cookies, or a body.
	//
	// Types that are valid to be assigned to Location:
	//	*HTTPMeta_Path
	//	*HTTPMeta_Query
	//	*HTTPMeta_Header
	//	*HTTPMeta_Cookie
	//	*HTTPMeta_Body
	//	*HTTPMeta_Empty
	//	*HTTPMeta_Auth
	//	*HTTPMeta_Multipart
	Location isHTTPMeta_Location `protobuf_oneof:"location"`
	// Response code with which this data is returned.
	// Should be 0 if this data is an argument.
	// Should be -1 if this data is the default response.
	ResponseCode         int32    `protobuf:"varint,7,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPMeta) Reset()         { *m = HTTPMeta{} }
func (m *HTTPMeta) String() string { return proto.CompactTextString(m) }
func (*HTTPMeta) ProtoMessage()    {}
func (*HTTPMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{24}
}

func (m *HTTPMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPMeta.Unmarshal(m, b)
}
func (m *HTTPMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPMeta.Marshal(b, m, deterministic)
}
func (m *HTTPMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPMeta.Merge(m, src)
}
func (m *HTTPMeta) XXX_Size() int {
	return xxx_messageInfo_HTTPMeta.Size(m)
}
func (m *HTTPMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPMeta.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPMeta proto.InternalMessageInfo

type isHTTPMeta_Location interface {
	isHTTPMeta_Location()
}

type HTTPMeta_Path struct {
	Path *HTTPPath `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type HTTPMeta_Query struct {
	Query *HTTPQuery `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

type HTTPMeta_Header struct {
	Header *HTTPHeader `protobuf:"bytes,3,opt,name=header,proto3,oneof"`
}

type HTTPMeta_Cookie struct {
	Cookie *HTTPCookie `protobuf:"bytes,4,opt,name=cookie,proto3,oneof"`
}

type HTTPMeta_Body struct {
	Body *HTTPBody `protobuf:"bytes,5,opt,name=body,proto3,oneof"`
}

type HTTPMeta_Empty struct {
	Empty *HTTPEmpty `protobuf:"bytes,6,opt,name=empty,proto3,oneof"`
}

type HTTPMeta_Auth struct {
	Auth *HTTPAuth `protobuf:"bytes,8,opt,name=auth,proto3,oneof"`
}

type HTTPMeta_Multipart struct {
	Multipart *HTTPMultipart `protobuf:"bytes,9,opt,name=multipart,proto3,oneof"`
}

func (*HTTPMeta_Path) isHTTPMeta_Location() {}

func (*HTTPMeta_Query) isHTTPMeta_Location() {}

func (*HTTPMeta_Header) isHTTPMeta_Location() {}

func (*HTTPMeta_Cookie) isHTTPMeta_Location() {}

func (*HTTPMeta_Body) isHTTPMeta_Location() {}

func (*HTTPMeta_Empty) isHTTPMeta_Location() {}

func (*HTTPMeta_Auth) isHTTPMeta_Location() {}

func (*HTTPMeta_Multipart) isHTTPMeta_Location() {}

func (m *HTTPMeta) GetLocation() isHTTPMeta_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *HTTPMeta) GetPath() *HTTPPath {
	if x, ok := m.GetLocation().(*HTTPMeta_Path); ok {
		return x.Path
	}
	return nil
}

func (m *HTTPMeta) GetQuery() *HTTPQuery {
	if x, ok := m.GetLocation().(*HTTPMeta_Query); ok {
		return x.Query
	}
	return nil
}

func (m *HTTPMeta) GetHeader() *HTTPHeader {
	if x, ok := m.GetLocation().(*HTTPMeta_Header); ok {
		return x.Header
	}
	return nil
}

func (m *HTTPMeta) GetCookie() *HTTPCookie {
	if x, ok := m.GetLocation().(*HTTPMeta_Cookie); ok {
		return x.Cookie
	}
	return nil
}

func (m *HTTPMeta) GetBody() *HTTPBody {
	if x, ok := m.GetLocation().(*HTTPMeta_Body); ok {
		return x.Body
	}
	return nil
}

func (m *HTTPMeta) GetEmpty() *HTTPEmpty {
	if x, ok := m.GetLocation().(*HTTPMeta_Empty); ok {
		return x.Empty
	}
	return nil
}

func (m *HTTPMeta) GetAuth() *HTTPAuth {
	if x, ok := m.GetLocation().(*HTTPMeta_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *HTTPMeta) GetMultipart() *HTTPMultipart {
	if x, ok := m.GetLocation().(*HTTPMeta_Multipart); ok {
		return x.Multipart
	}
	return nil
}

func (m *HTTPMeta) GetResponseCode() int32 {
	if m != nil {
		return m.ResponseCode
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HTTPMeta) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HTTPMeta_Path)(nil),
		(*HTTPMeta_Query)(nil),
		(*HTTPMeta_Header)(nil),
		(*HTTPMeta_Cookie)(nil),
		(*HTTPMeta_Body)(nil),
		(*HTTPMeta_Empty)(nil),
		(*HTTPMeta_Auth)(nil),
		(*HTTPMeta_Multipart)(nil),
	}
}

type DataMeta struct {
	// Types that are valid to be assigned to Meta:
	//	*DataMeta_Grpc
	//	*DataMeta_Http
	Meta                 isDataMeta_Meta `protobuf_oneof:"meta"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DataMeta) Reset()         { *m = DataMeta{} }
func (m *DataMeta) String() string { return proto.CompactTextString(m) }
func (*DataMeta) ProtoMessage()    {}
func (*DataMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{25}
}

func (m *DataMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMeta.Unmarshal(m, b)
}
func (m *DataMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMeta.Marshal(b, m, deterministic)
}
func (m *DataMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMeta.Merge(m, src)
}
func (m *DataMeta) XXX_Size() int {
	return xxx_messageInfo_DataMeta.Size(m)
}
func (m *DataMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DataMeta proto.InternalMessageInfo

type isDataMeta_Meta interface {
	isDataMeta_Meta()
}

type DataMeta_Grpc struct {
	Grpc *GRPCMeta `protobuf:"bytes,1,opt,name=grpc,proto3,oneof"`
}

type DataMeta_Http struct {
	Http *HTTPMeta `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

func (*DataMeta_Grpc) isDataMeta_Meta() {}

func (*DataMeta_Http) isDataMeta_Meta() {}

func (m *DataMeta) GetMeta() isDataMeta_Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DataMeta) GetGrpc() *GRPCMeta {
	if x, ok := m.GetMeta().(*DataMeta_Grpc); ok {
		return x.Grpc
	}
	return nil
}

func (m *DataMeta) GetHttp() *HTTPMeta {
	if x, ok := m.GetMeta().(*DataMeta_Http); ok {
		return x.Http
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataMeta) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataMeta_Grpc)(nil),
		(*DataMeta_Http)(nil),
	}
}

type ExampleValue struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleValue) Reset()         { *m = ExampleValue{} }
func (m *ExampleValue) String() string { return proto.CompactTextString(m) }
func (*ExampleValue) ProtoMessage()    {}
func (*ExampleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{26}
}

func (m *ExampleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleValue.Unmarshal(m, b)
}
func (m *ExampleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleValue.Marshal(b, m, deterministic)
}
func (m *ExampleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleValue.Merge(m, src)
}
func (m *ExampleValue) XXX_Size() int {
	return xxx_messageInfo_ExampleValue.Size(m)
}
func (m *ExampleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleValue.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleValue proto.InternalMessageInfo

type Data struct {
	// Types that are valid to be assigned to Value:
	//	*Data_Primitive
	//	*Data_Struct
	//	*Data_List
	//	*Data_Optional
	//	*Data_Oneof
	Value isData_Value `protobuf_oneof:"value"`
	// The meta field describes how this Data should be encoded in the target API
	// format (i.e. HTTP or gRPC).
	// For HTTP, only the top-level Data contains meta. For example, if Data is a
	// struct with HTTPBody in meta, it means "encode the full struct in the body
	// for the HTTP request/response." This applies to OneOf as well - all OneOf
	// options within the same Data share the same meta field in Data and each
	// option has an empty meta field.
	Meta *DataMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	// True if the data can be represented by null. This is only meaningful when
	// the Data represents a type rather than a concrete value.
	//
	// Nullable is different from Optional:
	// - Optional means that the value can be omitted
	// - Nullable means that we can use null as the value
	Nullable bool `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	// Example of values represented by this data. This is for informational
	// purpose only, so we use string to encode values and this field is not
	// included in pbhash.
	ExampleValues        map[string]*ExampleValue `protobuf:"bytes,8,rep,name=example_values,json=exampleValues,proto3" json:"example_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{27}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

type isData_Value interface {
	isData_Value()
}

type Data_Primitive struct {
	Primitive *Primitive `protobuf:"bytes,1,opt,name=primitive,proto3,oneof"`
}

type Data_Struct struct {
	Struct *Struct `protobuf:"bytes,2,opt,name=struct,proto3,oneof"`
}

type Data_List struct {
	List *List `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type Data_Optional struct {
	Optional *Optional `protobuf:"bytes,4,opt,name=optional,proto3,oneof"`
}

type Data_Oneof struct {
	Oneof *OneOf `protobuf:"bytes,6,opt,name=oneof,proto3,oneof"`
}

func (*Data_Primitive) isData_Value() {}

func (*Data_Struct) isData_Value() {}

func (*Data_List) isData_Value() {}

func (*Data_Optional) isData_Value() {}

func (*Data_Oneof) isData_Value() {}

func (m *Data) GetValue() isData_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Data) GetPrimitive() *Primitive {
	if x, ok := m.GetValue().(*Data_Primitive); ok {
		return x.Primitive
	}
	return nil
}

func (m *Data) GetStruct() *Struct {
	if x, ok := m.GetValue().(*Data_Struct); ok {
		return x.Struct
	}
	return nil
}

func (m *Data) GetList() *List {
	if x, ok := m.GetValue().(*Data_List); ok {
		return x.List
	}
	return nil
}

func (m *Data) GetOptional() *Optional {
	if x, ok := m.GetValue().(*Data_Optional); ok {
		return x.Optional
	}
	return nil
}

func (m *Data) GetOneof() *OneOf {
	if x, ok := m.GetValue().(*Data_Oneof); ok {
		return x.Oneof
	}
	return nil
}

func (m *Data) GetMeta() *DataMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Data) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Data) GetExampleValues() map[string]*ExampleValue {
	if m != nil {
		return m.ExampleValues
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Data_Primitive)(nil),
		(*Data_Struct)(nil),
		(*Data_List)(nil),
		(*Data_Optional)(nil),
		(*Data_Oneof)(nil),
	}
}

type MethodID struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiType              ApiType  `protobuf:"varint,2,opt,name=api_type,json=apiType,proto3,enum=api_spec.ApiType" json:"api_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodID) Reset()         { *m = MethodID{} }
func (m *MethodID) String() string { return proto.CompactTextString(m) }
func (*MethodID) ProtoMessage()    {}
func (*MethodID) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{28}
}

func (m *MethodID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodID.Unmarshal(m, b)
}
func (m *MethodID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodID.Marshal(b, m, deterministic)
}
func (m *MethodID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodID.Merge(m, src)
}
func (m *MethodID) XXX_Size() int {
	return xxx_messageInfo_MethodID.Size(m)
}
func (m *MethodID) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodID.DiscardUnknown(m)
}

var xxx_messageInfo_MethodID proto.InternalMessageInfo

func (m *MethodID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MethodID) GetApiType() ApiType {
	if m != nil {
		return m.ApiType
	}
	return ApiType_GRPC
}

type GRPCMethodMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GRPCMethodMeta) Reset()         { *m = GRPCMethodMeta{} }
func (m *GRPCMethodMeta) String() string { return proto.CompactTextString(m) }
func (*GRPCMethodMeta) ProtoMessage()    {}
func (*GRPCMethodMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{29}
}

func (m *GRPCMethodMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GRPCMethodMeta.Unmarshal(m, b)
}
func (m *GRPCMethodMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GRPCMethodMeta.Marshal(b, m, deterministic)
}
func (m *GRPCMethodMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GRPCMethodMeta.Merge(m, src)
}
func (m *GRPCMethodMeta) XXX_Size() int {
	return xxx_messageInfo_GRPCMethodMeta.Size(m)
}
func (m *GRPCMethodMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_GRPCMethodMeta.DiscardUnknown(m)
}

var xxx_messageInfo_GRPCMethodMeta proto.InternalMessageInfo

type HTTPMethodMeta struct {
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// The request-URI as defined by RFC 2616 section 5.1.
	// May contain path parameters in the form of `{key}` for substitution
	// at runtime (e.g. `/user/{user_name}`). For substitution to happen, a
	// corresponding `HTTPPath` Data must exist in the args of the method, with
	// the `HTTPPath.Key` field set to the same value as the format string (e.g.
	// `HTTPPath{ key: "user_name" }`) or else the substitution does not occur
	// and the path is used as is.
	PathTemplate string `protobuf:"bytes,2,opt,name=path_template,json=pathTemplate,proto3" json:"path_template,omitempty"`
	Host         string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// Processing latency in milliseconds.  This is 0 in specs, or if it
	// has not been measured (in an existing trace, or a request without
	// a corresponding response.)
	//
	// This measurement is from the last byte of the HTTP request to the
	// first byte of the HTTP response, ignoring time spent in transmission.
	ProcessingLatency    float32  `protobuf:"fixed32,4,opt,name=processing_latency,json=processingLatency,proto3" json:"processing_latency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPMethodMeta) Reset()         { *m = HTTPMethodMeta{} }
func (m *HTTPMethodMeta) String() string { return proto.CompactTextString(m) }
func (*HTTPMethodMeta) ProtoMessage()    {}
func (*HTTPMethodMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{30}
}

func (m *HTTPMethodMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPMethodMeta.Unmarshal(m, b)
}
func (m *HTTPMethodMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPMethodMeta.Marshal(b, m, deterministic)
}
func (m *HTTPMethodMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPMethodMeta.Merge(m, src)
}
func (m *HTTPMethodMeta) XXX_Size() int {
	return xxx_messageInfo_HTTPMethodMeta.Size(m)
}
func (m *HTTPMethodMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPMethodMeta.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPMethodMeta proto.InternalMessageInfo

func (m *HTTPMethodMeta) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPMethodMeta) GetPathTemplate() string {
	if m != nil {
		return m.PathTemplate
	}
	return ""
}

func (m *HTTPMethodMeta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HTTPMethodMeta) GetProcessingLatency() float32 {
	if m != nil {
		return m.ProcessingLatency
	}
	return 0
}

type MethodMeta struct {
	// Types that are valid to be assigned to Meta:
	//	*MethodMeta_Grpc
	//	*MethodMeta_Http
	Meta                 isMethodMeta_Meta `protobuf_oneof:"meta"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MethodMeta) Reset()         { *m = MethodMeta{} }
func (m *MethodMeta) String() string { return proto.CompactTextString(m) }
func (*MethodMeta) ProtoMessage()    {}
func (*MethodMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{31}
}

func (m *MethodMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodMeta.Unmarshal(m, b)
}
func (m *MethodMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodMeta.Marshal(b, m, deterministic)
}
func (m *MethodMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodMeta.Merge(m, src)
}
func (m *MethodMeta) XXX_Size() int {
	return xxx_messageInfo_MethodMeta.Size(m)
}
func (m *MethodMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MethodMeta proto.InternalMessageInfo

type isMethodMeta_Meta interface {
	isMethodMeta_Meta()
}

type MethodMeta_Grpc struct {
	Grpc *GRPCMethodMeta `protobuf:"bytes,1,opt,name=grpc,proto3,oneof"`
}

type MethodMeta_Http struct {
	Http *HTTPMethodMeta `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

func (*MethodMeta_Grpc) isMethodMeta_Meta() {}

func (*MethodMeta_Http) isMethodMeta_Meta() {}

func (m *MethodMeta) GetMeta() isMethodMeta_Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *MethodMeta) GetGrpc() *GRPCMethodMeta {
	if x, ok := m.GetMeta().(*MethodMeta_Grpc); ok {
		return x.Grpc
	}
	return nil
}

func (m *MethodMeta) GetHttp() *HTTPMethodMeta {
	if x, ok := m.GetMeta().(*MethodMeta_Http); ok {
		return x.Http
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MethodMeta) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MethodMeta_Grpc)(nil),
		(*MethodMeta_Http)(nil),
	}
}

type Method struct {
	Id *MethodID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// For HTTP REST APIs, the keys in this map have no meaning.
	Args map[string]*Data `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// For HTTP REST APIs, the keys in this map have no meaning.
	Responses            map[string]*Data `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Meta                 *MethodMeta      `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d10d17d32e60d7d, []int{32}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetId() *MethodID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Method) GetArgs() map[string]*Data {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Method) GetResponses() map[string]*Data {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *Method) GetMeta() *MethodMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterEnum("api_spec.HTTPAuth_HTTPAuthType", HTTPAuth_HTTPAuthType_name, HTTPAuth_HTTPAuthType_value)
	proto.RegisterEnum("api_spec.HTTPBody_ContentType", HTTPBody_ContentType_name, HTTPBody_ContentType_value)
	proto.RegisterType((*Bool)(nil), "api_spec.Bool")
	proto.RegisterType((*Bytes)(nil), "api_spec.Bytes")
	proto.RegisterType((*String)(nil), "api_spec.String")
	proto.RegisterType((*Int32)(nil), "api_spec.Int32")
	proto.RegisterType((*Int64)(nil), "api_spec.Int64")
	proto.RegisterType((*Uint32)(nil), "api_spec.Uint32")
	proto.RegisterType((*Uint64)(nil), "api_spec.Uint64")
	proto.RegisterType((*Double)(nil), "api_spec.Double")
	proto.RegisterType((*Float)(nil), "api_spec.Float")
	proto.RegisterType((*Primitive)(nil), "api_spec.Primitive")
	proto.RegisterMapType((map[string]bool)(nil), "api_spec.Primitive.FormatsEntry")
	proto.RegisterType((*List)(nil), "api_spec.List")
	proto.RegisterType((*Struct)(nil), "api_spec.Struct")
	proto.RegisterMapType((map[string]*Data)(nil), "api_spec.Struct.FieldsEntry")
	proto.RegisterType((*None)(nil), "api_spec.None")
	proto.RegisterType((*Optional)(nil), "api_spec.Optional")
	proto.RegisterType((*OneOf)(nil), "api_spec.OneOf")
	proto.RegisterMapType((map[string]*Data)(nil), "api_spec.OneOf.OptionsEntry")
	proto.RegisterType((*GRPCMeta)(nil), "api_spec.GRPCMeta")
	proto.RegisterType((*HTTPPath)(nil), "api_spec.HTTPPath")
	proto.RegisterType((*HTTPQuery)(nil), "api_spec.HTTPQuery")
	proto.RegisterType((*HTTPHeader)(nil), "api_spec.HTTPHeader")
	proto.RegisterType((*HTTPAuth)(nil), "api_spec.HTTPAuth")
	proto.RegisterType((*HTTPCookie)(nil), "api_spec.HTTPCookie")
	proto.RegisterType((*HTTPBody)(nil), "api_spec.HTTPBody")
	proto.RegisterType((*HTTPMultipart)(nil), "api_spec.HTTPMultipart")
	proto.RegisterType((*HTTPEmpty)(nil), "api_spec.HTTPEmpty")
	proto.RegisterType((*HTTPMeta)(nil), "api_spec.HTTPMeta")
	proto.RegisterType((*DataMeta)(nil), "api_spec.DataMeta")
	proto.RegisterType((*ExampleValue)(nil), "api_spec.ExampleValue")
	proto.RegisterType((*Data)(nil), "api_spec.Data")
	proto.RegisterMapType((map[string]*ExampleValue)(nil), "api_spec.Data.ExampleValuesEntry")
	proto.RegisterType((*MethodID)(nil), "api_spec.MethodID")
	proto.RegisterType((*GRPCMethodMeta)(nil), "api_spec.GRPCMethodMeta")
	proto.RegisterType((*HTTPMethodMeta)(nil), "api_spec.HTTPMethodMeta")
	proto.RegisterType((*MethodMeta)(nil), "api_spec.MethodMeta")
	proto.RegisterType((*Method)(nil), "api_spec.Method")
	proto.RegisterMapType((map[string]*Data)(nil), "api_spec.Method.ArgsEntry")
	proto.RegisterMapType((map[string]*Data)(nil), "api_spec.Method.ResponsesEntry")
}

func init() { proto.RegisterFile("method.proto", fileDescriptor_4d10d17d32e60d7d) }

var fileDescriptor_4d10d17d32e60d7d = []byte{
	// 1606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xcd, 0x72, 0xdb, 0x46,
	0x12, 0xe6, 0xbf, 0xc0, 0x26, 0xc5, 0x85, 0xc6, 0x5a, 0x2f, 0x8b, 0xeb, 0xb5, 0xb5, 0xb0, 0x2b,
	0x56, 0x39, 0x0a, 0x95, 0xa2, 0x14, 0x25, 0xe5, 0xaa, 0x1c, 0x48, 0x8a, 0x32, 0x65, 0x4b, 0xa2,
	0x02, 0xd1, 0x89, 0x93, 0x0b, 0x0b, 0x22, 0x87, 0x22, 0x4a, 0x20, 0x06, 0x01, 0x86, 0x4e, 0xf8,
	0x08, 0xb9, 0xe5, 0x21, 0x72, 0xcc, 0x13, 0xe4, 0x90, 0xf7, 0x48, 0x55, 0x1e, 0x26, 0xd5, 0x33,
	0x03, 0x10, 0xe0, 0x8f, 0x2f, 0xbe, 0x81, 0xd3, 0x5f, 0x77, 0x7f, 0x33, 0xfd, 0x4d, 0x37, 0x40,
	0x28, 0x4f, 0x29, 0x9f, 0xb0, 0x51, 0xdd, 0xf3, 0x19, 0x67, 0x44, 0xb3, 0x3c, 0x7b, 0x10, 0x78,
	0x74, 0x58, 0xab, 0xe0, 0x13, 0x9f, 0x7b, 0x54, 0x5a, 0x6a, 0x25, 0x7c, 0x0e, 0xe4, 0x0f, 0xe3,
	0x14, 0x72, 0x2d, 0xc6, 0x1c, 0xf2, 0x09, 0xe4, 0x70, 0xb9, 0x9a, 0xde, 0x4b, 0xef, 0x97, 0x1a,
	0xa4, 0x1e, 0x7a, 0xd7, 0xd1, 0xda, 0x9f, 0x7b, 0xd4, 0x14, 0x76, 0xb2, 0x0b, 0xf9, 0xf7, 0x96,
	0x33, 0xa3, 0xd5, 0xcc, 0x5e, 0x7a, 0x5f, 0x33, 0xe5, 0x0f, 0xe3, 0x0c, 0xf2, 0xad, 0x39, 0xa7,
	0x01, 0x79, 0x9e, 0x08, 0xf3, 0x20, 0x16, 0x06, 0xcd, 0x9b, 0xe2, 0x94, 0xc3, 0x38, 0x5d, 0x28,
	0xdc, 0x70, 0xdf, 0x76, 0xef, 0xc8, 0x7e, 0x22, 0xd0, 0xee, 0x22, 0x90, 0xb4, 0x6f, 0x8a, 0x54,
	0x8c, 0x31, 0x3a, 0x77, 0xf9, 0x51, 0x63, 0x33, 0x23, 0x61, 0xde, 0x14, 0x27, 0x9f, 0x8c, 0x73,
	0x72, 0xfc, 0xc1, 0x38, 0x27, 0xc7, 0x9b, 0xe2, 0x64, 0x63, 0x3b, 0x7b, 0x6b, 0x0b, 0x42, 0x1b,
	0x77, 0x26, 0xed, 0x9b, 0x22, 0x6d, 0x2f, 0x45, 0x3a, 0x39, 0xfe, 0x70, 0xa4, 0xcd, 0x9c, 0x72,
	0xb1, 0x48, 0xa7, 0x6c, 0x76, 0xeb, 0xd0, 0xcd, 0x91, 0xa4, 0x7d, 0x53, 0xa4, 0x74, 0xec, 0x94,
	0xce, 0x1c, 0x66, 0xf1, 0xcd, 0xa7, 0x24, 0xcc, 0x9b, 0xe2, 0x64, 0xc2, 0x38, 0xbf, 0x15, 0xa0,
	0x78, 0xed, 0xdb, 0x53, 0x9b, 0xdb, 0xef, 0x29, 0xf9, 0x2f, 0x14, 0x11, 0x3b, 0x98, 0xd8, 0x2e,
	0x17, 0x11, 0x8b, 0xa6, 0x86, 0x0b, 0x5d, 0xdb, 0xe5, 0xe4, 0x10, 0xe0, 0x96, 0x31, 0x67, 0xb0,
	0x88, 0x52, 0x6a, 0x54, 0x92, 0xb2, 0xed, 0xa6, 0xcc, 0x22, 0x62, 0xbe, 0x45, 0x08, 0x69, 0x40,
	0xe9, 0x16, 0x45, 0xa8, 0x3c, 0xb2, 0xc2, 0xe3, 0x5f, 0x4b, 0x0a, 0xed, 0xa6, 0x4c, 0x10, 0x28,
	0xe9, 0xf3, 0x05, 0x94, 0x03, 0xa1, 0x37, 0xe5, 0x94, 0x13, 0x4e, 0xfa, 0xb2, 0x1a, 0xbb, 0x29,
	0xb3, 0x24, 0x71, 0x51, 0x2a, 0x51, 0x4b, 0xe5, 0x95, 0x5f, 0x4e, 0x25, 0xa4, 0x87, 0xa9, 0x04,
	0x2a, 0xee, 0x73, 0x72, 0xac, 0x7c, 0x0a, 0x6b, 0x7c, 0x4e, 0x8e, 0x95, 0xcf, 0xc9, 0x71, 0x44,
	0x6f, 0x16, 0x4f, 0xb4, 0xb5, 0x4c, 0x4f, 0x4a, 0x0a, 0xe9, 0xcd, 0x62, 0xa9, 0x94, 0x5b, 0x94,
	0x4b, 0x5b, 0xe7, 0x26, 0x92, 0x95, 0x66, 0xc9, 0x6c, 0x23, 0x21, 0x07, 0xe5, 0x56, 0x5c, 0x76,
	0x93, 0x62, 0x41, 0x37, 0x89, 0x8b, 0x36, 0x36, 0xc6, 0xe2, 0x2b, 0x2f, 0x58, 0xde, 0x98, 0x50,
	0x06, 0x6e, 0x4c, 0xa0, 0xa4, 0xcf, 0x2b, 0xd8, 0xb1, 0xee, 0x6d, 0x6e, 0x0d, 0x2c, 0xd7, 0x65,
	0xdc, 0xe2, 0x36, 0x73, 0x83, 0x6a, 0x49, 0x78, 0xd6, 0x16, 0x9e, 0x4d, 0x84, 0x34, 0x17, 0x08,
	0x53, 0xb7, 0x96, 0x56, 0x48, 0x03, 0xfe, 0x3d, 0x64, 0x2e, 0xb7, 0x6c, 0x37, 0x18, 0xf8, 0x96,
	0x3b, 0x62, 0x53, 0x45, 0xa3, 0x2c, 0xda, 0xd7, 0x83, 0xd0, 0x68, 0x0a, 0x9b, 0x4c, 0xfe, 0x12,
	0xb6, 0xc6, 0xcc, 0x9f, 0x5a, 0x3c, 0xa8, 0x6e, 0xef, 0x65, 0xf7, 0x4b, 0x8d, 0xbd, 0x45, 0xca,
	0x48, 0x9c, 0xf5, 0x33, 0x09, 0xe9, 0xb8, 0xdc, 0x9f, 0x9b, 0xa1, 0x03, 0x79, 0x02, 0x25, 0xf9,
	0x38, 0xb8, 0xb7, 0xdd, 0x51, 0xb5, 0x22, 0x44, 0x0b, 0x72, 0xe9, 0x8d, 0xed, 0x8e, 0x6a, 0x2f,
	0xa1, 0x1c, 0xf7, 0x24, 0x3a, 0x64, 0xef, 0xe9, 0x5c, 0xa9, 0x1b, 0x1f, 0xd7, 0x77, 0xd8, 0x97,
	0x99, 0xaf, 0xd2, 0xad, 0x2d, 0x65, 0x31, 0x0e, 0x20, 0x77, 0x61, 0x07, 0x9c, 0x3c, 0x83, 0x3c,
	0x75, 0xe8, 0x34, 0xa8, 0xa6, 0x05, 0xcf, 0x98, 0xfc, 0x4f, 0x2d, 0x6e, 0x99, 0xd2, 0x68, 0xfc,
	0x92, 0x16, 0x5d, 0x75, 0x36, 0xe4, 0xe4, 0x18, 0x0a, 0x63, 0x9b, 0x3a, 0xa3, 0xd0, 0xe3, 0x51,
	0x42, 0xc9, 0xb3, 0x21, 0xaf, 0x9f, 0x09, 0xb3, 0xdc, 0x95, 0xc2, 0xd6, 0xce, 0xa1, 0x14, 0x5b,
	0x5e, 0x43, 0xf9, 0x59, 0x9c, 0xf2, 0x1a, 0x1e, 0xd1, 0x16, 0x8c, 0x02, 0xe4, 0xae, 0x98, 0x4b,
	0x8d, 0x01, 0x68, 0x3d, 0x0f, 0x4b, 0x64, 0x39, 0xe4, 0x19, 0xe4, 0x46, 0x16, 0xb7, 0x54, 0xcf,
	0x58, 0x72, 0xee, 0xa6, 0x4c, 0x61, 0x45, 0x94, 0xcb, 0xdc, 0x35, 0x29, 0x30, 0x1e, 0xa2, 0xd0,
	0xba, 0x38, 0xa2, 0x3f, 0xd2, 0x90, 0xef, 0xb9, 0xb4, 0x37, 0x26, 0x27, 0xb0, 0xc5, 0x3c, 0xa9,
	0xa0, 0x95, 0x4d, 0x0b, 0x44, 0x5d, 0x32, 0x09, 0x4b, 0xa9, 0xc0, 0xe4, 0x33, 0x20, 0x1e, 0xe3,
	0xd4, 0xe5, 0xb6, 0xe5, 0x0c, 0x86, 0xcc, 0x1d, 0x3b, 0xf6, 0x90, 0xab, 0xa2, 0xec, 0x44, 0x96,
	0xb6, 0x32, 0xd4, 0x5e, 0x43, 0x39, 0x1e, 0xe7, 0xa3, 0x4e, 0x09, 0x40, 0x7b, 0x65, 0x5e, 0xb7,
	0x2f, 0x29, 0xb7, 0x8c, 0x47, 0xa0, 0x75, 0xfb, 0xfd, 0xeb, 0x6b, 0x8b, 0x4f, 0x56, 0x63, 0x1a,
	0xff, 0x83, 0x22, 0x5a, 0xbf, 0x99, 0xd1, 0x75, 0x29, 0x8d, 0xc7, 0x00, 0x68, 0xee, 0x52, 0x6b,
	0x44, 0xfd, 0x35, 0xf6, 0x40, 0x06, 0x6f, 0xce, 0xf8, 0x84, 0x1c, 0xc5, 0x5a, 0x77, 0xa5, 0xf1,
	0x64, 0xc1, 0x2e, 0x44, 0x44, 0x0f, 0x8b, 0x36, 0x6e, 0x34, 0xa0, 0x1c, 0x5f, 0x25, 0x25, 0xd8,
	0x7a, 0x7b, 0xf5, 0xe6, 0xaa, 0xf7, 0xdd, 0x95, 0x9e, 0x22, 0x45, 0xc8, 0xb7, 0x9a, 0x37, 0xe7,
	0x6d, 0x3d, 0x4d, 0x00, 0x0a, 0xad, 0x4e, 0xd3, 0xec, 0x98, 0x7a, 0x26, 0x24, 0xd5, 0x66, 0xec,
	0xde, 0xa6, 0x6b, 0x48, 0xfd, 0x99, 0x96, 0xac, 0x5a, 0x6c, 0x34, 0x27, 0x4d, 0x28, 0xe3, 0x1d,
	0xa5, 0x2e, 0x1f, 0xc4, 0xd8, 0x3d, 0x4e, 0xb2, 0x43, 0x64, 0xbd, 0x2d, 0x61, 0x82, 0x5c, 0x69,
	0xb8, 0xf8, 0x61, 0x30, 0x28, 0xc5, 0x6c, 0x49, 0x8a, 0x1a, 0xe4, 0x5e, 0xdf, 0xf4, 0xae, 0xf4,
	0x34, 0xd9, 0x05, 0xfd, 0xac, 0x67, 0x5e, 0x0e, 0xde, 0x9a, 0x17, 0x83, 0xce, 0x55, 0xbb, 0x77,
	0xda, 0x39, 0xd5, 0x33, 0x44, 0x87, 0x72, 0xaf, 0xdd, 0xef, 0xf4, 0x07, 0x37, 0x7d, 0xb3, 0xd3,
	0xbc, 0xd4, 0xb3, 0x64, 0x0b, 0xb2, 0xd7, 0xa7, 0x67, 0x7a, 0x8e, 0x54, 0x00, 0xfa, 0x9d, 0x77,
	0xfd, 0xc1, 0xf5, 0x45, 0xf3, 0xfc, 0x4a, 0xcf, 0x63, 0xa8, 0xef, 0x9b, 0x97, 0x17, 0x7a, 0xc1,
	0x78, 0x0a, 0xdb, 0xc8, 0xea, 0x72, 0xe6, 0x70, 0xdb, 0xb3, 0x7c, 0x4e, 0x48, 0xec, 0x68, 0x8b,
	0xea, 0xe4, 0x4a, 0xb2, 0x72, 0x9d, 0xa9, 0xc7, 0xe7, 0xc6, 0xef, 0x59, 0xb9, 0x65, 0xac, 0x38,
	0x0e, 0x63, 0xcf, 0xe2, 0x93, 0xd5, 0x57, 0xb1, 0x50, 0x07, 0xa8, 0x76, 0x44, 0x90, 0x4f, 0x21,
	0xff, 0x23, 0x56, 0x5e, 0x29, 0xea, 0x41, 0x12, 0x2a, 0x44, 0xd1, 0x4d, 0x99, 0x12, 0x43, 0xea,
	0x50, 0x98, 0x08, 0x1d, 0xa8, 0xd1, 0xb7, 0x9b, 0x44, 0x4b, 0x8d, 0x74, 0x53, 0xa6, 0x42, 0x21,
	0x7e, 0x28, 0x4a, 0xa4, 0xa6, 0xde, 0x12, 0x5e, 0x96, 0x0f, 0xf1, 0x12, 0x85, 0xb4, 0x6f, 0xd9,
	0x68, 0xae, 0xa6, 0x1d, 0x59, 0xad, 0x10, 0xd2, 0x46, 0x04, 0xd2, 0xa6, 0xb8, 0x6d, 0x35, 0xe4,
	0x96, 0x68, 0x8b, 0x13, 0x41, 0xda, 0x02, 0x83, 0x61, 0xad, 0x19, 0x9f, 0xa8, 0x21, 0x45, 0x56,
	0x65, 0x89, 0x61, 0x11, 0x41, 0xbe, 0x84, 0xe2, 0x34, 0x3c, 0x72, 0x35, 0x9c, 0xfe, 0x93, 0x84,
	0x47, 0x15, 0xc1, 0x37, 0x83, 0x08, 0x4b, 0x9e, 0xc2, 0xb6, 0x4f, 0x03, 0x8f, 0xb9, 0x01, 0x1d,
	0x0c, 0xd9, 0x48, 0xce, 0xd1, 0xbc, 0x59, 0x0e, 0x17, 0xdb, 0x6c, 0x44, 0x5b, 0x00, 0x9a, 0xc3,
	0x86, 0x62, 0xac, 0x18, 0x63, 0xd0, 0xf0, 0xca, 0x86, 0xd5, 0xba, 0xf3, 0xbd, 0xe1, 0x6a, 0xb5,
	0xc2, 0x1b, 0x8c, 0xfc, 0x10, 0x81, 0xc8, 0x09, 0xe7, 0x9e, 0x2a, 0xd6, 0xd2, 0x4e, 0x42, 0x24,
	0x22, 0x5a, 0x05, 0xc8, 0x4d, 0xf1, 0xee, 0x57, 0xa0, 0xdc, 0xf9, 0xd9, 0x9a, 0x7a, 0x6a, 0x94,
	0x1a, 0x7f, 0x65, 0x21, 0x87, 0x89, 0xc9, 0x11, 0x14, 0xbd, 0x70, 0x12, 0xad, 0xbe, 0x6b, 0x45,
	0x43, 0x0a, 0xb7, 0x19, 0xe1, 0xc8, 0x0b, 0x28, 0x04, 0xa2, 0xc9, 0x2b, 0x06, 0xfa, 0x72, 0xf3,
	0xc7, 0x62, 0x4a, 0x04, 0x76, 0x5b, 0xc7, 0x0e, 0xb8, 0x92, 0x4a, 0xac, 0x55, 0xe1, 0xdc, 0x41,
	0x9e, 0x68, 0x25, 0x9f, 0x83, 0xc6, 0x54, 0x17, 0x57, 0x22, 0x89, 0xed, 0x2a, 0xec, 0xef, 0xdd,
	0x94, 0x19, 0xa1, 0xc8, 0x73, 0xc8, 0x33, 0x97, 0xb2, 0xf1, 0xea, 0xfb, 0x8d, 0x68, 0xc5, 0x58,
	0x76, 0x61, 0xc7, 0xef, 0x11, 0x3c, 0x82, 0x55, 0x35, 0x85, 0x07, 0x6f, 0x0a, 0x3b, 0xa9, 0x81,
	0xe6, 0xce, 0x1c, 0xc7, 0xba, 0x75, 0x64, 0xd9, 0x34, 0x33, 0xfa, 0x4d, 0xba, 0x50, 0xa1, 0xf2,
	0xf8, 0xe4, 0xd0, 0x0f, 0xaa, 0x9a, 0x18, 0x00, 0xff, 0x4f, 0x46, 0xab, 0xc7, 0xcf, 0x58, 0x4d,
	0x81, 0x6d, 0x1a, 0x5f, 0xab, 0xbd, 0x03, 0xb2, 0x0a, 0x5a, 0xd3, 0xe2, 0x0f, 0x92, 0x2d, 0xfe,
	0xe1, 0x22, 0x51, 0xdc, 0x7d, 0xed, 0x4c, 0xbf, 0x00, 0xed, 0x52, 0x7c, 0xbf, 0x9d, 0x9f, 0x62,
	0xbf, 0x70, 0xad, 0x69, 0xd4, 0x2f, 0xf0, 0x99, 0x1c, 0x80, 0x16, 0x7e, 0xc7, 0x89, 0xe8, 0x95,
	0xc6, 0x4e, 0xec, 0x4d, 0xc8, 0xb3, 0x45, 0xdf, 0xdb, 0xb2, 0xe4, 0x83, 0xa1, 0x43, 0x45, 0xe9,
	0x6f, 0xc2, 0x46, 0x62, 0x8e, 0xfc, 0x9a, 0x86, 0x8a, 0x12, 0x9a, 0x5a, 0x22, 0x0f, 0xa1, 0x20,
	0x3f, 0x19, 0x55, 0x22, 0xf5, 0x0b, 0xef, 0x03, 0xb6, 0x97, 0x01, 0xa7, 0x53, 0xcf, 0xb1, 0x78,
	0xf8, 0x65, 0x55, 0xc6, 0xc5, 0xbe, 0x5a, 0x43, 0x8e, 0x13, 0xa6, 0x14, 0x52, 0x34, 0xc5, 0xb3,
	0x18, 0x99, 0x3e, 0x1b, 0xd2, 0x20, 0xc0, 0x57, 0x66, 0x84, 0xb9, 0xc3, 0xb9, 0x50, 0x46, 0xc6,
	0xdc, 0x59, 0x58, 0x2e, 0xa4, 0xc1, 0xe0, 0x00, 0x31, 0x36, 0xf5, 0xc4, 0x45, 0xaa, 0xae, 0x5c,
	0x24, 0x85, 0x8b, 0xae, 0x53, 0x3d, 0x71, 0x9d, 0xaa, 0x2b, 0xd7, 0x29, 0x86, 0x4f, 0x5c, 0xaa,
	0xbf, 0x33, 0x50, 0x90, 0x66, 0x62, 0x40, 0xc6, 0x1e, 0xad, 0xde, 0xdc, 0xb0, 0x0e, 0x66, 0xc6,
	0x1e, 0x61, 0x1a, 0xcb, 0xbf, 0x0b, 0xaa, 0x19, 0x21, 0x9d, 0xda, 0x32, 0xaa, 0xde, 0xf4, 0xef,
	0x94, 0x66, 0x04, 0x8e, 0x7c, 0x0d, 0xc5, 0xb0, 0x6f, 0x04, 0xd5, 0xac, 0x70, 0x7a, 0xb2, 0xe2,
	0x64, 0x86, 0x08, 0xe9, 0xb9, 0xf0, 0xc0, 0x26, 0x21, 0x74, 0xbf, 0xd2, 0x73, 0x17, 0x3b, 0x92,
	0xca, 0xaf, 0xbd, 0x82, 0x62, 0x94, 0xfb, 0x63, 0xde, 0x36, 0x6a, 0x17, 0x50, 0x49, 0xf2, 0xf9,
	0x98, 0x68, 0xad, 0x83, 0x1f, 0x5e, 0x88, 0xb7, 0xf0, 0x80, 0x8d, 0xf9, 0x4f, 0x96, 0x4f, 0xeb,
	0x43, 0x36, 0x3d, 0x0c, 0x66, 0x1e, 0xf5, 0x03, 0x6e, 0xf9, 0x87, 0xde, 0xed, 0xe1, 0x1d, 0x3b,
	0x0c, 0xbd, 0x6f, 0x0b, 0xe2, 0x5f, 0x88, 0xa3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xec, 0x02,
	0x10, 0x86, 0xbc, 0x10, 0x00, 0x00,
}
