// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package api_spec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APISpec struct {
	// The type/signature of each method in the API spec.
	Methods []*Method `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	// User-supplied key value pairs associated with this spec.
	Tags                 map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *APISpec) Reset()         { *m = APISpec{} }
func (m *APISpec) String() string { return proto.CompactTextString(m) }
func (*APISpec) ProtoMessage()    {}
func (*APISpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}

func (m *APISpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APISpec.Unmarshal(m, b)
}
func (m *APISpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APISpec.Marshal(b, m, deterministic)
}
func (m *APISpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APISpec.Merge(m, src)
}
func (m *APISpec) XXX_Size() int {
	return xxx_messageInfo_APISpec.Size(m)
}
func (m *APISpec) XXX_DiscardUnknown() {
	xxx_messageInfo_APISpec.DiscardUnknown(m)
}

var xxx_messageInfo_APISpec proto.InternalMessageInfo

func (m *APISpec) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *APISpec) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type MethodCalls struct {
	// Instantiated methods with concrete argument and response values, as
	// observed from actual API calls.
	Calls                []*Method `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MethodCalls) Reset()         { *m = MethodCalls{} }
func (m *MethodCalls) String() string { return proto.CompactTextString(m) }
func (*MethodCalls) ProtoMessage()    {}
func (*MethodCalls) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{1}
}

func (m *MethodCalls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodCalls.Unmarshal(m, b)
}
func (m *MethodCalls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodCalls.Marshal(b, m, deterministic)
}
func (m *MethodCalls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodCalls.Merge(m, src)
}
func (m *MethodCalls) XXX_Size() int {
	return xxx_messageInfo_MethodCalls.Size(m)
}
func (m *MethodCalls) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodCalls.DiscardUnknown(m)
}

var xxx_messageInfo_MethodCalls proto.InternalMessageInfo

func (m *MethodCalls) GetCalls() []*Method {
	if m != nil {
		return m.Calls
	}
	return nil
}

func init() {
	proto.RegisterType((*APISpec)(nil), "api_spec.APISpec")
	proto.RegisterMapType((map[string]string)(nil), "api_spec.APISpec.TagsEntry")
	proto.RegisterType((*MethodCalls)(nil), "api_spec.MethodCalls")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_423806180556987f) }

var fileDescriptor_423806180556987f = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2e, 0x48, 0x4d,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2c, 0xc8, 0x8c, 0x07, 0xf1, 0xa5, 0x78,
	0x72, 0x53, 0x4b, 0x32, 0xf2, 0x53, 0x20, 0xe2, 0x4a, 0xf3, 0x19, 0xb9, 0xd8, 0x1d, 0x03, 0x3c,
	0x83, 0x0b, 0x52, 0x93, 0x85, 0xb4, 0xb8, 0xd8, 0x21, 0x72, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a,
	0xdc, 0x46, 0x02, 0x7a, 0x30, 0x5d, 0x7a, 0xbe, 0x60, 0x89, 0x20, 0x98, 0x02, 0x21, 0x7d, 0x2e,
	0x96, 0x92, 0xc4, 0xf4, 0x62, 0x09, 0x26, 0xb0, 0x42, 0x69, 0x84, 0x42, 0xa8, 0x61, 0x7a, 0x21,
	0x89, 0xe9, 0xc5, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x60, 0x85, 0x52, 0xe6, 0x5c, 0x9c, 0x70,
	0x21, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10,
	0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x06, 0xe1, 0x58,
	0x31, 0x59, 0x30, 0x2a, 0x99, 0x72, 0x71, 0x43, 0x2c, 0x77, 0x4e, 0xcc, 0xc9, 0x29, 0x16, 0x52,
	0xe3, 0x62, 0x4d, 0x06, 0x31, 0x70, 0x3a, 0x11, 0x22, 0xed, 0xa4, 0x13, 0xa5, 0x95, 0x98, 0x9d,
	0x59, 0x92, 0x58, 0x9c, 0x9f, 0x56, 0x52, 0x9e, 0x58, 0x94, 0xaa, 0x97, 0x9c, 0x9f, 0xab, 0x5f,
	0x5c, 0x5a, 0x90, 0x5a, 0x54, 0x5c, 0x92, 0x58, 0xa4, 0x5f, 0x90, 0xa4, 0x9f, 0x9e, 0xaf, 0x0f,
	0xd3, 0x9b, 0xc4, 0x06, 0x0e, 0x0d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x72, 0x00,
	0xba, 0x33, 0x01, 0x00, 0x00,
}
